name: CI-CD Terraform + Ansible

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    env:
      # fallback envs (Terraform also accepts -var below)
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_my_ip_cidr: ${{ secrets.MY_IP_CIDR }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    outputs:
      ips: ${{ steps.get_ips.outputs.ips }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create keys folder and write public key
        run: |
          mkdir -p keys
          # write public key exactly as stored in Secrets (no added newlines)
          printf '%s' "${{ secrets.SSH_PUBLIC_KEY }}" > keys/deployer.pub
          chmod 644 keys/deployer.pub

      - name: Debug: show public key exists & length (will not print secret content)
        run: |

